proxy:
  appserver:
    # To use a custom domain, define it here. You will also need to add it
    # to your /etc/hosts file or use a DNS tool (such as dnsmasq) to resolve
    # the domain to 127.0.0.1
    - drupal-demo.loc

services:
  appserver:
    # Set this to "true" to enable Xdebug.
    xdebug: false
    config:
      # Define a path to a custom php.ini file.
      php: .lando/php.ini
    overrides:
      environment:
        # Use the custom domain in Drush URIs.
        DRUSH_OPTIONS_URI: "https://drupal-demo.loc"

  database:
    # Customize the database credentials.
    creds:
      user: drupal
      password: drupal
      database: drupal
